# -*- coding: utf-8 -*-
"""CDT_Caso-estudio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbCBV0Fi9ziLbeWNuL1vTpa_5Yx71bRK
"""

# Caso de estudio: Proyección de certificado de depósito a término (CDT)
# 01240372038 - Diego Ardila Quintero

# Librerías
# Caso de estudio: Proyección de certificado de depósito a término (CDT)
import gradio as gr
import pandas as pd

COLS_REG = ["Registro", "Plazo", "Monto inicial"]
COLS_CDT = ["Mes", "Intereses", "Monto final"]

# ---------- Datos: dos listas paralelas ----------
# registros[i]      -> [num_registro, plazo, monto_inicial]
# proyecciones[i]   -> [(mes, interes, saldo), ...]  (la proyección del registro i)
registros = []
proyecciones = []


# ---------- Lógica ----------
def tasa_mensual(plazo):
    return 0.001695 * plazo + 0.0983


def validar_datos(monto, plazo):
    if monto is None or monto <= 0:
        raise gr.Error("El monto inicial debe ser mayor que 0.")
    if plazo is None or plazo <= 1 or int(plazo) != plazo:
        raise gr.Error("El plazo debe ser un número entero de meses mayor que 1.")


def validar_indice(n):
    if n is None or not (1 <= n <= len(registros)):
        raise gr.Error(f"Ingrese un número de registro válido (1 a {len(registros)}).")


def calcular_proyeccion(monto, plazo):
    tasa = tasa_mensual(plazo)
    saldo = monto
    filas = [(0, 0, round(monto, 2))]  # mes 0
    for mes in range(1, int(plazo) + 1):
        interes = saldo * (tasa / 100)
        saldo += interes
        filas.append((mes, round(interes, 2), round(saldo, 2)))
    return filas


# ---------- Helpers para mostrar ----------
def df_registros():
    return pd.DataFrame(registros, columns=COLS_REG)


def df_proyeccion(n):
    if n and 1 <= n <= len(registros):
        return pd.DataFrame(proyecciones[int(n) - 1], columns=COLS_CDT)
    return pd.DataFrame(columns=COLS_CDT)


def resumen(n):
    if not (n and 1 <= n <= len(registros)):
        return ""
    _, plazo, monto = registros[int(n) - 1]
    saldo_final = proyecciones[int(n) - 1][-1][2]
    return (f"**Registro {int(n)}** — Saldo final: ${saldo_final:,.2f} | "
            f"Tasa mensual aplicada: {tasa_mensual(plazo):.4f}% | "
            f"Total de intereses: ${saldo_final - monto:,.2f}")


def refrescar(n):
    """Devuelve: tabla registros, tabla CDT, resumen, # del próximo registro, registro mostrado"""
    return df_registros(), df_proyeccion(n), resumen(n), len(registros) + 1, n


# ---------- Operaciones ----------
def agregar(monto, plazo):
    validar_datos(monto, plazo)
    registros.append([len(registros) + 1, int(plazo), monto])
    proyecciones.append(calcular_proyeccion(monto, plazo))
    return refrescar(len(registros))


def editar(indice, monto, plazo):
    validar_indice(indice)
    validar_datos(monto, plazo)
    i = int(indice) - 1
    registros[i] = [int(indice), int(plazo), monto]
    proyecciones[i] = calcular_proyeccion(monto, plazo)
    return refrescar(int(indice))


def eliminar(indice):
    validar_indice(indice)
    i = int(indice) - 1
    del registros[i]
    del proyecciones[i]
    for pos, reg in enumerate(registros):  # renumerar
        reg[0] = pos + 1
    return refrescar(min(int(indice), len(registros)))


def mostrar(n):
    validar_indice(n)
    return df_proyeccion(n), resumen(n)


def guardar_csv():
    if not registros:
        raise gr.Error("No hay registros para guardar.")
    # Archivo 1: registros
    df_registros().to_csv("registros_cdt.csv", index=False, encoding="utf-8")
    # Archivo 2: todas las proyecciones, enlazadas por la columna "Registro"
    filas = [(i + 1, *fila) for i, proy in enumerate(proyecciones) for fila in proy]
    pd.DataFrame(filas, columns=["Registro"] + COLS_CDT).to_csv(
        "proyecciones_cdt.csv", index=False, encoding="utf-8")
    return ["registros_cdt.csv", "proyecciones_cdt.csv"]


# ---------- Interfaz ----------
with gr.Blocks() as interfaz:
    gr.Markdown("# Registro de CDT")
    gr.Markdown("Ingrese los datos para calcular el CDT")

    with gr.Row():
        with gr.Column():
            numUsuario = gr.Number(label="# de registro", interactive=False, value=1)
            initialMoney = gr.Number(label="Cantidad de dinero inicial (ej: 1000000)", minimum=1)
            timeToUse = gr.Number(label="Plazo en meses (ej: 12)", minimum=2, precision=0)

        with gr.Column():
            gr.Markdown("### Operaciones")
            btnAdd = gr.Button("Agregar registro")
            btnEdit = gr.Button("Editar registro")
            btnDelete = gr.Button("Eliminar registro")
            btnSave = gr.Button("Guardar CSV")
            gr.Markdown("Para editar o eliminar, indique el número de registro según la tabla.")
            indexUserInput = gr.Number(label="Número de registro", precision=0, minimum=1)

        with gr.Column():
            archivoSalida = gr.File(label="Archivos CSV", file_count="multiple")

    tablaRegistro = gr.Dataframe(headers=COLS_REG, label="Registros")

    with gr.Row():
        choice = gr.Number(label="Registro que desea mostrar", precision=0, minimum=1)
        btnShow = gr.Button("Mostrar proyección")
    textoResumen = gr.Markdown()
    tablaCDT = gr.Dataframe(headers=COLS_CDT, label="Proyección del CDT")

    salidas = [tablaRegistro, tablaCDT, textoResumen, numUsuario, choice]
    btnAdd.click(agregar, [initialMoney, timeToUse], salidas)
    btnEdit.click(editar, [indexUserInput, initialMoney, timeToUse], salidas)
    btnDelete.click(eliminar, [indexUserInput], salidas)
    btnShow.click(mostrar, [choice], [tablaCDT, textoResumen])
    btnSave.click(guardar_csv, outputs=archivoSalida)

interfaz.launch(debug=True)
