# -*- coding: utf-8 -*-
"""CDT_Caso-estudio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbCBV0Fi9ziLbeWNuL1vTpa_5Yx71bRK
"""

# Caso de estudio: Proyección de certificado de depósito a término (CDT)
# 01240372038 - Diego Ardila Quintero

# Librerías
import gradio as gr
import pandas as pd
import csv
import os
# ----------
"""
Requisitos:
DatosCDT => Monto inicial + Plazo
Validación => Monto inicial > 0 y Plazo > 1 || Si dato inválido, informar sobre el error y solicitar el dato nuevamente
# Formula para Tasa Mensual (%) => 0,001695 * Plazo * 0,0983
# Cada mes:
- Interés = Saldo Anterior * (Tasa/100)
- Saldo nuevo = Saldo Anterior + Interés

# Tabla de resultados, contener
Mes | Intereses | Saldo final del mes
inicia en mes 0

# Resultado final
Saldo que recibirá al finalizar el plazo, la tasa aplicada, total de intereses ganados
"""
# ----------

def listToDict(usersList):
  result = []
  for i in usersList:
    if i == "" or not isinstance(i, list):
      continue
    result.append({
        'Usuario':i[0],
        'Identificacion':i[1],
        'Nombre':i[2],
        'Masa':i[3],
        'Estatura':i[4],
        'IMC-Calculado':i[5],
        'Masa-Max':i[6]
    })
  return pd.DataFrame(result)


def newUser(initialAmount,time):
  global numUser
  numUser += 1
  actualUser = [] # Vacia la lista

  tasaMensual = 0.001695 * time + 0.0983
  saldoBefore = initialAmount
  _i = 0
  while _i < time:
    _i += 1
    interes = saldoBefore * (tasaMensual/100)
    saldoNew = saldoBefore + interes
    saldoBefore = saldoNew


  #                 0
  actualUser = []
  listUsers.append(actualUser)

  return listToDict(listUsers)

# Interfaz
with gr.Blocks() as interfaz:

  gr.Markdown("# Registro de usuarios")
  gr.Markdown("Ingrese los datos del usuario")

  with gr.Row():
    with gr.Column():
      identificacion = gr.Number(
          placeholder=12345678,
          label="Identificación (C.C)",
          precision=0,  # Cuando no se requieren decimales
          minimum=0
      )

      nombre = gr.Textbox(
          label="Nombre",
          placeholder="Juanito Perez",
          max_length=30
      )

      masa = gr.Number(
          label="Masa (Kg)",
          placeholder=80,
          minimum=0
      )

      estatura = gr.Number(
          label="Estatura (Metros)",
          placeholder=1.72,
          minimum=0
      )

    with gr.Column():
      gr.Markdown("### Operaciones")

      btnAdd= gr.Button("Agregar usuario")
      btnEdit = gr.Button("Editar usuario")
      btnDelete = gr.Button("Eliminar usuario")
      btnSave = gr.Button("Guardar CSV")

      rangeMaxUsers= len(listUsers)
      if rangeMaxUsers == 0:
        msg = "Aún no hay datos disponibles"
      else:
        msg = "1 - ",rangeMaxUsers

      gr.Markdown(f"Ingrese un valor si va a eliminar o editar. De lo contrario déjelo vacío. Recuerde el número máximo de usuario según la tabla de resultados")
      indexUserInput = gr.Number(
          label="Número de usuario",
          precision=0,
          minimum=1,
          maximum=rangeMaxUsers
      )

    with gr.Column():
      archivoSalida = gr.File(
          label="Archivo CSV"
      )

  tabla = gr.Dataframe(
  headers=[
      "Usuario",
      "Identificación",
      "Nombre",
      "Masa",
      "Estatura",
      "IMC",
      "Masa Máxima"
  ],
  label="Usuarios registrados"
)

# Funciones de los botones
  btnAdd.click(
      fn=newUser,
      inputs=[identificacion,nombre,masa,estatura],
      outputs=tabla
     )

  btnEdit.click(
      fn=editUser,
      inputs=[indexUserInput,identificacion,nombre,masa,estatura],
      outputs=tabla
      )

  btnDelete.click(
      fn=deleteUser,
      inputs=[indexUserInput],
      outputs=tabla
      )

  btnSave.click(
      fn=saveCSV
  )

interfaz.launch(debug=True)

numUser = 0
listUsers = []

tasaMensual = 0.001695 * time + 0.0983
saldoBefore = initialAmount
_i = 0
while _i < time:
  _i += 1
  interes = saldoBefore * (tasaMensual/100)
  saldoNew = saldoBefore + interes
  saldoBefore = saldoNew